### ISSUE TITLE
Crash w/Texture Packer

### ISSUE THREAD

**Issue by meachware** [nicklockwood/LayerSprites#1]
Hi Nick - awesome work (yet again!!!) I created a sprite sheet (cocos2d format) with both TP and Zwoptex. The zwoptex file loads fine, the TP file crashes. Both are POW-2, exact same files and png. I'm using TP v3.0.11

Please let me know what else I can do to help - I'd prefer to use TP (w/encryption).
Greg

Error:
'**\* -[NSPathStore2 stringByAppendingPathExtension:]: nil argument'

**Comment by nicklockwood** [comment]
Can you paste the TP file into github (saves me having to recreate one).

**Comment by meachware** [comment]
Hey Nick,

n/p - here's a quick small test

Regards,
Greg

**Comment by nicklockwood** [comment]
OK, that should be fixed in 1.0.1
